version: 2

updates:
  - package-ecosystem: "gomod"
    directory: "/"
    labels: ["dependencies"]
    schedule:
      interval: "daily"
    groups:
      flux-deps:
        patterns:
          - "github.com/fluxcd/*"
      go-deps:
        patterns:
          - "*"
        exclude-patterns:
          - "github.com/fluxcd/*"
    allow:
      - dependency-type: "direct"
    ignore:
      # Kubernetes deps are updated by fluxcd/pkg
      - dependency-name: "k8s.io/*"
      - dependency-name: "sigs.k8s.io/*"
      # Cloud SDKs are updated by SOPS
      - dependency-name: "github.com/Azure/*"
      - dependency-name: "github.com/aws/*"
      # Flux APIs pkg are updated at release time
      - dependency-name: "github.com/fluxcd/kustomize-controller/api"
      - dependency-name: "github.com/fluxcd/source-controller/api"
  - package-ecosystem: "github-actions"
    directory: "/"
    labels: ["area/ci", "dependencies"]
    groups:
      ci:
        patterns:
          - "*"
    schedule:
      interval: "daily"
