apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8282"
    spec:
      containers:
      - name: manager
        image: fluxcd/kustomize-controller
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8282
            name: http-prom
        args:
        - --enable-leader-election
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 64Mi
      terminationGracePeriodSeconds: 10
