apiVersion: kustomize.fluxcd.io/v1alpha1
kind: Kustomization
metadata:
  name: podinfo-dev
spec:
  interval: 5m
  path: "./overlays/dev/"
  prune: "env=dev"
  gitRepositoryRef:
    name: podinfo
---
apiVersion: kustomize.fluxcd.io/v1alpha1
kind: Kustomization
metadata:
  name: podinfo-staging
spec:
  interval: 5m
  path: "./overlays/staging/"
  prune: "env=staging"
  gitRepositoryRef:
    name: podinfo
---
apiVersion: kustomize.fluxcd.io/v1alpha1
kind: Kustomization
metadata:
  name: podinfo-production
spec:
  interval: 5m
  path: "./overlays/production/"
  prune: "env=production"
  gitRepositoryRef:
    name: podinfo-releases
