name: e2e

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore Go cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup Go
        uses: actions/setup-go@v2-beta
        with:
          go-version: 1.14.x
      - name: Setup Kubernetes
        uses: engineerd/setup-kind@v0.3.0
      - name: Setup Kustomize
        uses: ./.github/actions/kustomize
      - name: Setup Kubebuilder
        uses: ./.github/actions/kubebuilder
      - name: Run tests
        run: make test
        env:
          KUBEBUILDER_ASSETS: ${{ github.workspace }}/kubebuilder/bin
      - name: Check if working tree is dirty
        run: |
          if [[ $(git diff --stat) != '' ]]; then
            echo 'run make test and commit changes'
            exit 1
          fi
      - name: Build container image
        run: make docker-build IMG=test/kustomize-controller:latest
        env:
          KUBEBUILDER_ASSETS: ${{ github.workspace }}/kubebuilder/bin
      - name: Load test image
        run: kind load docker-image test/kustomize-controller:latest
      - name: Deploy source-controller
        run: kustomize build https://github.com/fluxcd/source-controller//config/default?ref=v0.0.1-alpha.1 | kubectl apply -f-
      - name: Deploy kustomize-controller
        run: make dev-deploy IMG=test/kustomize-controller:latest
        env:
          KUBEBUILDER_ASSETS: ${{ github.workspace }}/kubebuilder/bin
      - name: Run smoke tests
        run: |
          kubectl apply -k ./config/testdata/webapp
          kubectl apply -k ./config/testdata/generate
          kubectl wait kustomizations/frontend --for=condition=ready --timeout=4m
          kubectl wait kustomizations/generate --for=condition=ready --timeout=4m
          kubectl -n kustomize-system logs deploy/kustomize-controller
      - name: Debug failure
        if: failure()
        run: |
          kubectl get gitrepositories -oyaml
          kubectl get kustomizations -oyaml
          kubectl -n kustomize-system get all
          kubectl -n kustomize-system logs deploy/kustomize-controller